export const TUTOR_LIST_REQUEST = "TUTOR_LIST_REQUEST";
export const TUTOR_LIST_SUCCESS = "TUTOR_LIST_SUCCESS";
export const TUTOR_LIST_FAIL = "TUTOR_LIST_FAIL";

export const SINGLE_TUTOR_LIST_REQUEST = "SINGLE_TUTOR_LIST_REQUEST";
export const SINGLE_TUTOR_LIST_SUCCESS = "SINGLE_TUTOR_LIST_SUCCESS";
export const SINGLE_TUTOR_LIST_FAIL = "SINGLE_TUTOR_LIST_FAIL";
