const tutors = [
  {
    _id: "1",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Platinum",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "2",
    name: "Hasibul Hasan",
    image: "https://bdtutors.com/pofiles/121823208_1181_16.02.05.001.jpg.jpg",
    type: "Platinum",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "3",
    name: "Abdullah Ali",
    image: "https://bdtutors.com/pofiles/3158214_2554_Photo.jpg.jpg",
    type: "Gold",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "4",
    name: "Shahriar Hasan",
    image: "https://bdtutors.com/pofiles/11713472_196_passport.JPG.jpg",
    type: "Silver",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "5",
    name: "Jesmin Mahmud",
    image: "https://bdtutors.com/pofiles/4158479_537_Passport%20photo.jpg.jpg",
    type: "Platinum",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "6",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Gold",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "7",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Silver",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "8",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Gold",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "9",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Platinum",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Chittagong",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "10",
    name: "Hasibul Hasan",
    image: "https://bdtutors.com/pofiles/111822784_9542_Ony%20recent.jpg.jpg",
    type: "Platinum",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "11",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Platinum",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Chittagong",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },

  {
    _id: "12",
    name: "Mushfiq Hasan",
    image: "https://bdtutors.com/pofiles/42142070_5668_sujan01-1.jpg.jpg",
    type: "Platinum",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01945643356",
      email: "knebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Chittagong",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["CSE", "KUET", "3.44", "2015", "none"],
    },
  },

  {
    _id: "13",
    name: "Fahim Arif",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Platinum",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Bogra",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["CSE", "CUET", "3.44", "2015", "none"],
    },
  },

  {
    _id: "14",
    name: "Moin Hasan",
    image: "https://bdtutors.com/pofiles/71820285_3231_PP%20photo.png.jpg",
    type: "Platinum",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "10000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["MBBS", "Dhaka Medical", "3.44", "2015", "none"],
    },
  },

  {
    _id: "15",
    name: "Sultana Akter",
    image:
      "https://bdtutors.com/pofiles/92039117_6209_received_2574158196025520.jpeg.jpg",
    type: "Platinum",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["BME", "BUET", "3.44", "2015", "none"],
    },
  },

  {
    _id: "16",
    name: "Hasan Abdullah",
    image: "https://bdtutors.com/pofiles/111933606_2071_DSC_3578%20(3).jpg.jpg",
    type: "Platinum",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["BBA", "NSU", "3.44", "2015", "none"],
    },
  },

  {
    _id: "17",
    name: "Akinuzzaman",
    image: "https://bdtutors.com/pofiles/21818327_1378_7.jpg.jpg",
    type: "Platinum",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "Dhaka University", "3.44", "2015", "none"],
    },
  },

  {
    _id: "18",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Platinum",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },

  {
    _id: "19",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Platinum",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },

  {
    _id: "20",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Platinum",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "21",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Gold",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "22",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Gold",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },

  {
    _id: "23",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Gold",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "24",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Gold",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "25",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Gold",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "26",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Gold",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "27",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Gold",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "28",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Gold",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "29",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Gold",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "30",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Gold",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "31",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Gold",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "32",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Gold",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
  {
    _id: "33",
    name: "Hasibul Hasan",
    image:
      "https://bdtutors.com/pofiles/41715020_8677_15443005_1195058630564707_1546995843082119510_o.jpg.jpg",
    type: "Gold",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "Dhaka University", "3.44", "2015", "none"],
    },
  },
  {
    _id: "34",
    name: "Jahirul Hasan",
    image: "https://bdtutors.com/pofiles/42142070_5668_sujan01-1.jpg.jpg",
    type: "Gold",
    basic_info: {
      reg_time: {
        member_since: "17-04-2017",
        last_login: "17-04-2020",
      },

      qualification: "B.Sc in EEE",
      phone: "01745673456",
      email: "kuettoanoynebnaht@yahoo.com",
      fb_link: "facebook.com/links",
      twitter_link: "twitter.com/fasd",
      linkdin_link: "linkdin.com/sdfasd",
    },
    tution_info: {
      expected_min_salary: "6000",
      current_status_for_tution: "Available",
      days_per_week: "3",
      prefferef_tutoring_style: "Private Tution",
      place_of_learning: "Home Visit",
      extra_facilities: "",
      preffered_medium: "Bangla",
      preffered_classes: ["Class ix", "ssc", "hsc"],
      preffered_subject: ["General Math", "Physics", "Chemistry"],
      preffered_area: {
        distict: "Dhaka",
        area: ["Badda", "Cantonment", "Gulshan"],
      },
    },
    educational_info: {
      ssc: [
        "science",
        "Khulna Zilla School",
        "A+",
        "2008",
        "Board Scholarship",
      ],
      hsc: [
        "science",
        "Khulna City College",
        "A+",
        "2010",
        "Board Scholarship",
      ],
      honors: ["EEE", "KUET", "3.44", "2015", "none"],
    },
  },
];

export { tutors };
